### PR TITLE
Add markup documentation on the level.json files

### PR DESCRIPTION
**Pull request by kaltinril**
@rowan-bulkow , per your request I've created a markdown/markup (whatever) document for the level.  It describes each field/variable in the JSON, gives examples, data types, etc.

### CODE REVIEW

**Comment by kaltinril** [comment]
@maxzaki , I added you mainly so you can see the level information and know about it.

**Comment by rowan-bulkow** [comment]
Looks great, thanks @kaltinril

**Comment by kaltinril** [comment]
@rowan-bulkow , you keep approving which is awesome, but you haven't been merging.
@maxzaki , I added a bunch more to this branch, if you want to review, approve, and merge.
@KenrickM , review if you want, approve if you want, merge if you want.

1. Simplified the squirrel class.
2. Pulled logic from squirrel into the base rotatable class since all objects will pretty much need to either 3. rotate, or be placed rotated on the wheel.
4. Got textures to be loaded using the asset manager with a main menu "loading" screen (Loads too fast to see).
5. Got eagles to be displayed and positioned/rotate based on the level1.json and level4.json file data.
6. Going to bed.

**Comment by rowan-bulkow** [comment]
@kaltinril . I guess that's a difference in process - at my workplace the owner of the branch usually merges after it gets approved. That said, I'm happy to simply start merging as a reviewer, although I think it would be great if @maxzaki got a chance to take a look at this one.

**Comment by kaltinril** [comment]
@rowan-bulkow , I agree.  And I'm fine with merging it, forces me to have to make sure it will merge also :p

@maxzaki , can you review, approve, and then let me know so I can merge it in.

**Pull request merged**
